version: 0.2

phases:
  pre_build:
    commands:
      - echo Checking AWS CLI version...
      - aws --version
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin public.ecr.aws/l4h4u4d1)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t prvi-repo .
      - docker tag prvi-repo:latest public.ecr.aws/l4h4u4d1/prvi-repo:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/l4h4u4d1/prvi-repo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"flask-kont","imageUri":"public.ecr.aws/l4h4u4d1/prvi-repo:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
